# Generated by Django 3.0.6 on 2020-06-03 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='itemDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
